Accessibility fixes
uktrade/export-wins-ui-mi pull request #263
Opened 2020-09-07 08:13 UTC by cgsunkel

2020-09-09 16:32 UTC, rachaelcodes commented on src/app/views/macros/hvc-remove-duplicates.html
> +{% macro removeDuplicateHvcs( globalHvcs ) %}
This seems like a lot of data cleaning logic to have at this layer of the app. Perhaps it would fit better as a script in `lib` that gets called at the `controller` stage (e.g. with the `globalSummary` here: https://github.com/uktrade/export-wins-ui-mi/blob/9b68adc5e6b36cfd1d0bbe3bfaa4a585865d91f3/src/app/controllers/controller.index.js). Of course, ideally, the fix is a database one...

2020-09-14 14:50 UTC, ambrozic approved these changes

2020-09-14 14:50 UTC, ambrozic commented on src/app/lib/view-models/remove-duplicate-hvcs.js
> +        if(isDuplicate == false) {
this should be triple or strict equality (`===`)

2020-09-14 15:32 UTC, paulgain requested changes

2020-09-14 15:32 UTC, paulgain commented on src/app/lib/view-models/remove-duplicate-hvcs.js
> +};
This is redundant, you can reduce all six lines (L17-L22) into one:
```js
module.exports = getUniqueHvcs
```

2020-09-14 15:32 UTC, paulgain commented on src/app/lib/view-models/remove-duplicate-hvcs.js
> +function getUniqueHvcs(globalHvcs){
Can you please log `globalHvcs ` and post the output here as we can improve this function.

2020-09-14 15:35 UTC, cgsunkel commented on src/app/lib/view-models/remove-duplicate-hvcs.js
> +function getUniqueHvcs(globalHvcs){
[
  { name: 'voluptatibus et aut', code: 'E35' },
  { name: 'accusamus minus inventore', code: 'E191' },
  { name: 'vitae tenetur quis', code: 'E25' },
  { name: 'itaque consequatur nobis', code: 'E14' },
  { name: 'veritatis aut repudiandae', code: 'E14' },
  { name: 'veritatis aut repudiandae', code: 'E14' },
  { name: 'veritatis aut repudiandae', code: 'E14' },
  { name: 'veritatis aut repudiandae', code: 'E14' },
  { name: 'test', code: 'E14' }
]

2020-09-14 16:34 UTC, paulgain commented on src/app/controllers/controller.index.js
> +		const globalHvcs = removeDuplicateHvcs.removeDuplicates(data.globalHvcs.results);
There are a few ways to tackle this: 

**Array.filter and Array.findIndex**
```js
const globalHvcs = data.globalHvcs.results.filter((hvc, index, self) =>
  index === self.findIndex((hvc2) => hvc.name === hvc2.name)
)
```

**Lodash**

You would have to add this dependency:

```js
const { uniqWith } = require('lodash')
...
const globalHvcs = uniqWith(data.globalHvcs.results, (elem, elem2) => elem.name === elem2.name)
```

You could then delete `src/app/lib/view-models/remove-duplicate-hvcs.js`

2020-09-15 09:05 UTC, rachaelcodes approved these changes

2020-09-15 09:12 UTC, paulgain approved these changes

2020-09-17 12:35 UTC, paulgain commented
Looking good!

2020-09-17 12:37 UTC, merged